package com.example.myapplication

class Datasource() {
    fun loadData(): List<Person> {
        return listOf(
            Person(R.string.name_1, R.string.address_1),
            Person(R.string.name_2, R.string.address_2),
            Person(R.string.name_3, R.string.address_3),
            Person(R.string.name_4, R.string.address_4),
            Person(R.string.name_5, R.string.address_5),
            Person(R.string.name_6, R.string.address_6),
            Person(R.string.name_7, R.string.address_7),
            Person(R.string.name_8, R.string.address_8),
            Person(R.string.name_9, R.string.address_9),
            Person(R.string.name_10, R.string.address_10),
            Person(R.string.name_11, R.string.address_11),
            Person(R.string.name_12, R.string.address_12),
            Person(R.string.name_13, R.string.address_13),
            Person(R.string.name_14, R.string.address_14),
            Person(R.string.name_15, R.string.address_15),
            Person(R.string.name_16, R.string.address_16),
            Person(R.string.name_17, R.string.address_17),
            Person(R.string.name_18, R.string.address_18),
            Person(R.string.name_19, R.string.address_19),
            Person(R.string.name_20, R.string.address_20),
            Person(R.string.name_21, R.string.address_21),
            Person(R.string.name_22, R.string.address_22),
            Person(R.string.name_23, R.string.address_23),
            Person(R.string.name_24, R.string.address_24),
            Person(R.string.name_25, R.string.address_25),
            Person(R.string.name_26, R.string.address_26),
            Person(R.string.name_27, R.string.address_27),
            Person(R.string.name_28, R.string.address_28),
            Person(R.string.name_29, R.string.address_29),
            Person(R.string.name_30, R.string.address_30),
            Person(R.string.name_31, R.string.address_31),
            Person(R.string.name_32, R.string.address_32),
            Person(R.string.name_33, R.string.address_33),
            Person(R.string.name_34, R.string.address_34),
            Person(R.string.name_35, R.string.address_35),
            Person(R.string.name_36, R.string.address_36),
            Person(R.string.name_37, R.string.address_37),
            Person(R.string.name_38, R.string.address_38),
            Person(R.string.name_39, R.string.address_39),
            Person(R.string.name_40, R.string.address_40),
            Person(R.string.name_41, R.string.address_41),
            Person(R.string.name_42, R.string.address_42),
            Person(R.string.name_43, R.string.address_43),
            Person(R.string.name_44, R.string.address_44),
            Person(R.string.name_45, R.string.address_45),
            Person(R.string.name_46, R.string.address_46)
        )
    }
}
